# action.yml
name: "Overleaf Sync with Git"
branding:
  icon: 'align-center'  
  color: 'yellow'
description: "🤖 A GitHub action to take backups from OverLeaf which is an Online LaTeX Editor."


inputs:
  OVERLEAF_COOKIE:
    description: "Active Cookie of overleaf account"
    required: true
  OVERLEAF_COOKIE_KEY:
    description: "The key of the cookie, default is overleaf_session2"
    default: "overleaf_session2"
  OVERLEAF_PROJECT_ID: # id of input
    description: "Id of the project you want the bot to take automatic snapshot"
    required: true
  OVERLEAF_HOST:
    description: "Hostname of your Overleaf Instance, default is www.overleaf.com"
    default: "www.overleaf.com"


runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.OVERLEAF_COOKIE }}
    - ${{ inputs.OVERLEAF_COOKIE_KEY }}
    - ${{ inputs.OVERLEAF_PROJECT_ID }}
    - ${{ inputs.OVERLEAF_HOST }}

